/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Espacial.Convolucion;
import java.awt.Image;

/**
 *
 * @author Abelardo
 */
public class JInternalFrameConvolucion extends javax.swing.JInternalFrame {
    private JInternalFrameImagen internal;
    private Image imagenOriginal , nueva;
  
    /**
     * Creates new form JInternalFrameConvolucion
     */
    public JInternalFrameConvolucion(JInternalFrameImagen internal) {
        initComponents();
        this.internal=internal;
        this.imagenOriginal= herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spin1 = new javax.swing.JSpinner();
        spin2 = new javax.swing.JSpinner();
        spin3 = new javax.swing.JSpinner();
        spin4 = new javax.swing.JSpinner();
        spin6 = new javax.swing.JSpinner();
        spin5 = new javax.swing.JSpinner();
        spin7 = new javax.swing.JSpinner();
        spin8 = new javax.swing.JSpinner();
        spin9 = new javax.swing.JSpinner();
        spin10 = new javax.swing.JSpinner();
        spin11 = new javax.swing.JSpinner();
        spin12 = new javax.swing.JSpinner();
        spin13 = new javax.swing.JSpinner();
        spin14 = new javax.swing.JSpinner();
        spin15 = new javax.swing.JSpinner();
        spin16 = new javax.swing.JSpinner();
        spin17 = new javax.swing.JSpinner();
        spin18 = new javax.swing.JSpinner();
        spin19 = new javax.swing.JSpinner();
        spin20 = new javax.swing.JSpinner();
        spin21 = new javax.swing.JSpinner();
        spin22 = new javax.swing.JSpinner();
        spin23 = new javax.swing.JSpinner();
        spin24 = new javax.swing.JSpinner();
        spin25 = new javax.swing.JSpinner();
        jSpinner26 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner27 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Convolución");

        jLabel1.setText("Divisor: ");

        spin1.setMinimumSize(new java.awt.Dimension(40, 20));
        spin1.setPreferredSize(new java.awt.Dimension(40, 20));

        spin2.setMinimumSize(new java.awt.Dimension(40, 20));
        spin2.setPreferredSize(new java.awt.Dimension(40, 20));

        spin3.setMinimumSize(new java.awt.Dimension(40, 20));
        spin3.setPreferredSize(new java.awt.Dimension(40, 20));

        spin4.setMinimumSize(new java.awt.Dimension(40, 20));
        spin4.setPreferredSize(new java.awt.Dimension(40, 20));

        spin6.setMinimumSize(new java.awt.Dimension(40, 20));
        spin6.setPreferredSize(new java.awt.Dimension(40, 20));

        spin5.setMinimumSize(new java.awt.Dimension(40, 20));
        spin5.setPreferredSize(new java.awt.Dimension(40, 20));

        spin7.setMinimumSize(new java.awt.Dimension(40, 20));
        spin7.setPreferredSize(new java.awt.Dimension(40, 20));

        spin8.setMinimumSize(new java.awt.Dimension(40, 20));
        spin8.setPreferredSize(new java.awt.Dimension(40, 20));

        spin9.setMinimumSize(new java.awt.Dimension(40, 20));
        spin9.setPreferredSize(new java.awt.Dimension(40, 20));

        spin10.setMinimumSize(new java.awt.Dimension(40, 20));
        spin10.setPreferredSize(new java.awt.Dimension(40, 20));

        spin11.setMinimumSize(new java.awt.Dimension(40, 20));
        spin11.setPreferredSize(new java.awt.Dimension(40, 20));

        spin12.setMinimumSize(new java.awt.Dimension(40, 20));
        spin12.setPreferredSize(new java.awt.Dimension(40, 20));

        spin13.setMinimumSize(new java.awt.Dimension(40, 20));
        spin13.setPreferredSize(new java.awt.Dimension(40, 20));

        spin14.setMinimumSize(new java.awt.Dimension(40, 20));
        spin14.setPreferredSize(new java.awt.Dimension(40, 20));

        spin15.setMinimumSize(new java.awt.Dimension(40, 20));
        spin15.setPreferredSize(new java.awt.Dimension(40, 20));

        spin16.setMinimumSize(new java.awt.Dimension(40, 20));
        spin16.setPreferredSize(new java.awt.Dimension(40, 20));

        spin17.setMinimumSize(new java.awt.Dimension(40, 20));
        spin17.setPreferredSize(new java.awt.Dimension(40, 20));

        spin18.setMinimumSize(new java.awt.Dimension(40, 20));
        spin18.setPreferredSize(new java.awt.Dimension(40, 20));

        spin19.setMinimumSize(new java.awt.Dimension(40, 20));
        spin19.setPreferredSize(new java.awt.Dimension(40, 20));

        spin20.setMinimumSize(new java.awt.Dimension(40, 20));
        spin20.setPreferredSize(new java.awt.Dimension(40, 20));

        spin21.setMinimumSize(new java.awt.Dimension(40, 20));
        spin21.setPreferredSize(new java.awt.Dimension(40, 20));

        spin22.setMinimumSize(new java.awt.Dimension(40, 20));
        spin22.setPreferredSize(new java.awt.Dimension(40, 20));

        spin23.setMinimumSize(new java.awt.Dimension(40, 20));
        spin23.setPreferredSize(new java.awt.Dimension(40, 20));

        spin24.setMinimumSize(new java.awt.Dimension(40, 20));
        spin24.setPreferredSize(new java.awt.Dimension(40, 20));

        spin25.setMinimumSize(new java.awt.Dimension(40, 20));
        spin25.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel2.setText("Offset:");

        jButton1.setText("Aplicar Mascara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mascaras Kirsch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spin6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spin2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spin11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spin14, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(spin19, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spin15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spin20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spin16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spin21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinner27, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                            .addComponent(jSpinner26, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double kernel[][] = {{(int)this.spin1.getValue(),(int)this.spin2.getValue(),(int)this.spin3.getValue(),(int)this.spin4.getValue(),(int)this.spin5.getValue()},
            {(int)this.spin6.getValue(),(int)this.spin7.getValue(),(int)this.spin8.getValue(),(int)this.spin9.getValue(),(int)this.spin10.getValue()},
            {(int)this.spin11.getValue(),(int)this.spin12.getValue(),(int)this.spin13.getValue(),(int)this.spin14.getValue(),(int)this.spin15.getValue()},
            {(int)this.spin16.getValue(),(int)this.spin17.getValue(),(int)this.spin18.getValue(),(int)this.spin19.getValue(),(int)this.spin20.getValue()},
            {(int)this.spin21.getValue(),(int)this.spin22.getValue(),(int)this.spin23.getValue(),(int)this.spin24.getValue(),(int)this.spin25.getValue()}};
        int divisor = (int) this.jSpinner26.getValue();
        int offset = (int) this.jSpinner27.getValue();
        Convolucion c = new Convolucion(imagenOriginal);
        Image nueva = c.aplicar(kernel, divisor, offset);
        internal.setImagen(nueva);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Convolucion c = new Convolucion(imagenOriginal);
        int divisor = (int) this.jSpinner26.getValue();
        Image nu = c.aplicarKirsch(divisor);
        internal.setImagen(nu);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner26;
    private javax.swing.JSpinner jSpinner27;
    private javax.swing.JSpinner spin1;
    private javax.swing.JSpinner spin10;
    private javax.swing.JSpinner spin11;
    private javax.swing.JSpinner spin12;
    private javax.swing.JSpinner spin13;
    private javax.swing.JSpinner spin14;
    private javax.swing.JSpinner spin15;
    private javax.swing.JSpinner spin16;
    private javax.swing.JSpinner spin17;
    private javax.swing.JSpinner spin18;
    private javax.swing.JSpinner spin19;
    private javax.swing.JSpinner spin2;
    private javax.swing.JSpinner spin20;
    private javax.swing.JSpinner spin21;
    private javax.swing.JSpinner spin22;
    private javax.swing.JSpinner spin23;
    private javax.swing.JSpinner spin24;
    private javax.swing.JSpinner spin25;
    private javax.swing.JSpinner spin3;
    private javax.swing.JSpinner spin4;
    private javax.swing.JSpinner spin5;
    private javax.swing.JSpinner spin6;
    private javax.swing.JSpinner spin7;
    private javax.swing.JSpinner spin8;
    private javax.swing.JSpinner spin9;
    // End of variables declaration//GEN-END:variables
}
