/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Espacial.Histograma;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import Espacial.Espacial;
/**
 *
 * @author Abelardo
 */
public class JInternalFrameGrises extends javax.swing.JFrame {

    /**
     * Creates new form JInternalFrameGrises
     */
    private JInternalFrameImagen internal,nuevo;
    
    private Espacial e;
        
    public JInternalFrameGrises( JInternalFrameImagen internal) {
       this.internal = internal;
       e = new Espacial();
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escalaGrises = new javax.swing.JButton();
        negativo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escalaGrises.setText("Escala de Grises");
        escalaGrises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalaGrisesActionPerformed(evt);
            }
        });

        negativo.setText("Negativo");
        negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escalaGrises, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(negativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escalaGrises)
                .addGap(18, 18, 18)
                .addComponent(negativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escalaGrisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalaGrisesActionPerformed
        // TODO add your handling code here:
        BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
        Image nueva = herramientas.HerramientasImagen.toImage(e.EscalaGrises(bi));
        internal.setImagen(nueva);
    }//GEN-LAST:event_escalaGrisesActionPerformed

    private void negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoActionPerformed
        // TODO add your handling code here:
        BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
        Image nueva = herramientas.HerramientasImagen.toImage(e.Negativo(bi));
        internal.setImagen(nueva);
    }//GEN-LAST:event_negativoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escalaGrises;
    private javax.swing.JButton negativo;
    // End of variables declaration//GEN-END:variables
}
