/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Espacial.Espacial;
import Espacial.Histograma;
import java.awt.Image;
import java.awt.image.BufferedImage;

/**
 *
 * @author Abelardo
 */
public class JInternalFrameExpansion extends javax.swing.JInternalFrame {
    private JInternalFrameImagen internal;
    private Image imagenOriginal , nueva;
   
    /**
     * Creates new form JInternalFrameExpansion
     */
    public JInternalFrameExpansion(JInternalFrameImagen internal) {
        this.internal = internal;
        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Lineal = new javax.swing.JButton();
        jSlider_expansion_logaritmica = new javax.swing.JSlider();
        jSlider_expansion_exponencial = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        btn_exponencial = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Expansión");

        btn_Lineal.setText("Expansión Lineal");
        btn_Lineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LinealActionPerformed(evt);
            }
        });

        jSlider_expansion_logaritmica.setMajorTickSpacing(25);
        jSlider_expansion_logaritmica.setMaximum(255);
        jSlider_expansion_logaritmica.setPaintLabels(true);
        jSlider_expansion_logaritmica.setPaintTicks(true);
        jSlider_expansion_logaritmica.setValue(0);

        jSlider_expansion_exponencial.setMajorTickSpacing(25);
        jSlider_expansion_exponencial.setMaximum(255);
        jSlider_expansion_exponencial.setPaintLabels(true);
        jSlider_expansion_exponencial.setPaintTicks(true);
        jSlider_expansion_exponencial.setValue(0);

        jButton1.setText("Ecualizador");

        btn_log.setText("Expansión Logaritmica");

        btn_exponencial.setText("Expansión Exponencial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSlider_expansion_exponencial, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jSlider_expansion_logaritmica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btn_log)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btn_Lineal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exponencial)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Lineal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSlider_expansion_logaritmica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_log)
                .addGap(18, 18, 18)
                .addComponent(jSlider_expansion_exponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_exponencial)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LinealActionPerformed
        // TODO add your handling code here:

        Histograma h = new Histograma(imagenOriginal);
        h.calcularHistograma();
        BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
        nueva = herramientas.HerramientasImagen.toImage(Espacial.expansionLineal(h, imagenOriginal));
        internal.setImagen(nueva);
    }//GEN-LAST:event_btn_LinealActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Lineal;
    private javax.swing.JButton btn_exponencial;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton jButton1;
    private javax.swing.JSlider jSlider_expansion_exponencial;
    private javax.swing.JSlider jSlider_expansion_logaritmica;
    // End of variables declaration//GEN-END:variables
}
